# Generated by Django 2.2 on 2019-05-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0002_auto_20190506_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
