# Generated by Django 2.2 on 2019-05-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0002_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='u2e_apply',
            old_name='institute',
            new_name='instituition',
        ),
    ]
