# Generated by Django 2.2 on 2019-05-08 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0003_rechargecard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name_plural': '竞拍信息'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '专家信息'},
        ),
        migrations.AlterModelOptions(
            name='bidding',
            options={'verbose_name_plural': '竞价记录信息'},
        ),
        migrations.AlterModelOptions(
            name='publish_apply',
            options={'verbose_name_plural': '发布资源申请'},
        ),
        migrations.AlterModelOptions(
            name='rechargecard',
            options={'verbose_name_plural': '充值卡信息'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name_plural': '科研资源信息'},
        ),
        migrations.AlterModelOptions(
            name='u2e_apply',
            options={'verbose_name_plural': '获取专家权限申请'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name_plural': '用户Token'},
        ),
        migrations.AlterField(
            model_name='auction',
            name='candidate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='SAcore.Author'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='SAcore.Author'),
        ),
    ]
