# Generated by Django 2.2 on 2019-05-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0004_auto_20190508_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
