# Generated by Django 2.2 on 2019-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAcore', '0007_auto_20190508_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='title',
        ),
        migrations.AlterField(
            model_name='auction',
            name='started_time',
            field=models.DateTimeField(),
        ),
    ]
